baseURL = "https://www.budibase.com/"
languageCode = "en-uk"
title = "Budibase - Build Life Changing SaaS Applications With Ease"
theme = "budibase"

[params]
author = "Joe Johnston"
keywords = ["SaaS Applications", "SaaS builder", "Application builder"]
description = "Budibase is the new abd better way to build software and SaaS applications. Budibase eliminates repetition and dramatically reduces development time. Check it out."
dateform = "Jan 2, 2006"
lang = "en"
googleAnalytics = ""


