baseURL = "https://www.budibase.com/"
languageCode = "en-uk"
title = "Budibase - All-in-one Web App Builder For Rapid Development"
theme = "budibase"
enableEmoji = "true"

copyright = "This work is licensed and owned by Budibase"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
keywords = ["SaaS Applications", "SaaS builder", "Application builder"]
description = "Budibase is a modern, open source web app builder for creating, hosting and managing applications. Budibase eliminates repetition and dramatically reduces development time. Check it out."
dateform = "Jan 2, 2006"
lang = "en"
googleAnalytics = ""

[author]
  name = "Joseph Johnston"


[params.publisher]
    name = "Budibase"

  [params.publisher.logo]
      url = "/budibase-logo-small.png"
      width = 127
      height = 40

  [params.logo]
    url = "/budibase-logo-small.png"
    width = 127
    height = 40

  [params.image]
    url = "/budibase-logo.png"
    width = 800
    height = 600