baseURL = "https://musing-noether-79adc3.netlify.com/"
languageCode = "en-uk"
title = "Budibase - A Better Way To Build SaaS Applications"
theme = "budibase"

[params]
author = "Joe Johnston"
keywords = ["SaaS Applications", "SaaS builder", "Application builder"]
description = "Budibase is the new and better way to build SaaS applications. Budibase eliminates repetition and dramatically reduces development time. Check it out."
dateform = "Jan 2, 2006"
lang = "en"
googleAnalytics = ""


