baseURL = "https://digijo.co.uk/"
languageCode = "en-us"
title = "DigiJo - Award Winning Digital Marketing Consultant Belfast"
theme = "hugo-theme-sarah"


[params]
author = "DigiJo"
description = "Digital marketing consultant based in Belfast, Northern Ireland. Award-winner in SEO, Social, and Web Design."
keywords = ["Digital Marketing", "Web Design", "SEO"]
avatar = "img/header-image.jpg"
dateform = "Jan 2, 2006"
lang = "en"
footertext = "written by Belfast Digital Marketing Expert DigiJo_"
about = """
I'm not in the marketing industry to serve people, I'm in the people industry to serve great digital marketing. As an award winning digital marketer from beautiful Belfast, I help local businesses reach their true potential. Before you know it, you'll be attracting and converting leads like you never thought possible.
"""

[params.social]
linkedin      = "linkedin.com/in/joejohnston1989"
twitter       = "https://twitter.com/joejohnston1989"

[[params.info]]
label = "Certified"
value = "Google Specialist"

[[params.infogd]]
label = "Certified"
value = "Adobe Masterclass"

[[params.projects]]
name = "Seven Technologies Group"
desc = "At Seven Technologies, I delivered a website that was, secure, super fast, and SEO-optimised. The design of the website is clean and impactful to represent the sector 7TG operate in."
img = "img/homepage/testimonials/7tg.jpg"
link = "https://www.7techgroup.com"

[[params.projects]]
name = "TM3"
desc = "At TM3 I co-ordinated with Eyekiller to design a beautiful, responsive website that was fully focused on converting visitors to leads - and it worked! SEO was a major focus with the TM3 website. Moving domain and keeping SEO juice was imperative. Thankfully, I managed the job perfectly, with the new domain authority jumping from 0 - 35 in 8 months. Icing on this beautiful cake, the website now ranks top of Google (#1!) for their prime keyword - Physio Software"
img = "img/homepage/testimonials/tm3.jpg"
link = "https://www.tm3pm.com/"

enableRobotsTXT = true
canonifyURLs = true
# and if you think your md file names or locations might change:
[permalinks]
    post = "/blog/:title/"

